# @package evaluators.main.env.env.params
defaults:
  - override /eval/initial_conditions@_here_: common_initial_conditions
  - _self_

simulation_box_params:
  box_size: [7000,7000,2000]
initial_conditions_params:
  tangent_position_parameters:
    starting_distance_from_tangent_position_m_normal_mean: ???
    starting_distance_from_tangent_position_m_normal_sigma: ???
    starting_distance_from_tangent_position_m_normal_sigma_k: 1.
    tangent_distance_from_core_m_normal_mean: ???
    tangent_distance_from_core_m_normal_sigma: ???
    tangent_distance_from_core_m_normal_sigma_k: 1.
  altitude_earth_m_mean: ???
  altitude_earth_m_sigma: 0.0
  altitude_earth_m_sigma_k: 1.
