# @package _global_
defaults:
- /eval/gaussian/initial_conditions@evaluators.main.env.env.params: gaussian_thermal_initial_conditions
- /eval/gaussian/air_velocity_fields@evaluators.main.env.env.air_velocity_field: eval12
- _self_
experiment_name: policy_eval12
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: eval12
        bird_name: bird_train_glider
