# @package _global_
defaults:
- /eval/gaussian/air_velocity_fields@evaluators.main.env.env.air_velocity_field: eval77
- _self_
experiment_name: multi_agent_policy_eval77
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: eval77
        bird_name: bird_train_glider
