# @package _global_
defaults:
- /eval/gaussian/air_velocity_fields@evaluators.main.env.env.air_velocity_field: eval39
- _self_
experiment_name: multi_agent_policy_eval39
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: eval39
        bird_name: bird_train_glider
