# @package _global_
defaults:
- /eval/gaussian/air_velocity_fields@evaluators.main.env.env.air_velocity_field: eval36
- _self_
experiment_name: multi_agent_policy_eval36
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: eval36
        bird_name: bird_train_glider
