defaults:
  - multi_agent_eval_policy_config
  # - override hydra/launcher: bird_ray
  - override logger@logger: local_tensorboard_logger
  - _self_

evaluators:
  main:
    # seed: 45
    episode_count: 1
    env:
      env:
        params:
          max_closest_agent_count: ???
          max_sequence_length: ???
hydra:
  callbacks:
    merge_observation_logs:
      _target_: utils.multirun_hydra_statistics_concat_callback.MultirunHydraStatisticsConcatCallback
      input:
        filepath: eval/main/observation_log.csv
        index_column:
        header: 0
      output:
        filename_prefix: merged_observation_log
        target_dir: ???
