# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b010_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b010_0.1/data.csv
    additional_columns:
      thermal: b010
      bird_name: Peaches
      mass_kg: 3.13
      wing_area_m2: 0.5111725498054359
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 839.3054
      original_thermal_z_max: 1298.9098
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Peaches
