# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b010_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b010_0.1/data.csv
    additional_columns:
      thermal: b010
      bird_name: Mirabell
      mass_kg: 2.73
      wing_area_m2: 0.4591587538868714
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 851.0928
      original_thermal_z_max: 1296.3907
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Mirabell
