# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b010_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b010_0.1/data.csv
    additional_columns:
      thermal: b010
      bird_name: Ekky
      mass_kg: 3.26
      wing_area_m2: 0.46188676208453744
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 813.3271
      original_thermal_z_max: 1288.4258
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Ekky
