# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b010_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b010_0.1/data.csv
    additional_columns:
      thermal: b010
      bird_name: Crisps
      mass_kg: 3.48
      wing_area_m2: 0.5929201247994635
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 824.9064
      original_thermal_z_max: 1039.1848
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Crisps
