# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b0230_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b023_0.1/data.csv
    additional_columns:
      thermal: b0230
      bird_name: Conchito
      mass_kg: 3.2
      wing_area_m2: 0.46056034650257677
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 947.059
      original_thermal_z_max: 1276.5702
    trajectory_converter:
      shift_time_s: 48626.0
      filters:
        bird_name: Conchito
