# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b0230_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b023_0.1/data.csv
    additional_columns:
      thermal: b0230
      bird_name: Betty
      mass_kg: 2.94
      wing_area_m2: 0.4944833153928956
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 477.3397
      original_thermal_z_max: 1100.4973
    trajectory_converter:
      shift_time_s: 48626.0
      filters:
        bird_name: Betty
