# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b072_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b072_0.1/data.csv
    additional_columns:
      thermal: b072
      bird_name: Fifi
      mass_kg: 2.95
      wing_area_m2: 0.42956858936228004
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 976.2014
      original_thermal_z_max: 1168.7304
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Fifi
