# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b072_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b072_0.1/data.csv
    additional_columns:
      thermal: b072
      bird_name: Tobi
      mass_kg: 3.39
      wing_area_m2: 0.5612606012442105
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 980.543
      original_thermal_z_max: 1043.9156
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Tobi
