# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b077_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b077_0.1/data.csv
    additional_columns:
      thermal: b077
      bird_name: Balou
      mass_kg: 3.27
      wing_area_m2: 0.5770013609821092
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 1243.3921
      original_thermal_z_max: 1474.4663
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Balou
