# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b077_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b077_0.1/data.csv
    additional_columns:
      thermal: b077
      bird_name: Ella
      mass_kg: 3.29
      wing_area_m2: 0.47622514709060454
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 1243.797
      original_thermal_z_max: 1402.0241
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Ella
