# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b112_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b112_0.2/data.csv
    additional_columns:
      thermal: b112
      bird_name: Fifi
      mass_kg: 2.95
      wing_area_m2: 0.42956858936228004
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 1355.5614
      original_thermal_z_max: 1562.4871
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Fifi
