# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b121_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b121_0.1/data.csv
    additional_columns:
      thermal: b121
      bird_name: Balou
      mass_kg: 3.27
      wing_area_m2: 0.5770013609821092
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 1340.9476
      original_thermal_z_max: 1688.6774
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Balou
