# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b121_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b121_0.1/data.csv
    additional_columns:
      thermal: b121
      bird_name: Kim
      mass_kg: 3.32
      wing_area_m2: 0.5441683591340707
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 1336.8541
      original_thermal_z_max: 1488.4294
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Kim
