# @package _global_
defaults:
- 'override /env/glider/air_velocity_field@job.air_velocity_field:': stacked_decomposed_realistic/b121_extrapolated
- _self_
job:
  params:
    trajectory_path: data/bird_comparison/processed/stork_trajectories/b121_0.1/data.csv
    additional_columns:
      thermal: b121
      bird_name: Ohnezahn
      mass_kg: 3.33
      wing_area_m2: 0.5284500528212013
      CL: 1.5
      CD: 0.09
      original_thermal_z_min: 1343.2406
      original_thermal_z_max: 1501.894
    trajectory_converter:
      shift_time_s: 0.0
      filters:
        bird_name: Ohnezahn
