# @package _global_
defaults:
  - ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
  - /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b121_extrapolated
  - _self_
experiment_name: multi_agent_policy_b121
evaluators:
  main:
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b121
          cutoff_params:
            success_altitude_m: 1691.8827
            fail_altitude_m: 840.9476
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 1472.
    observation_logger:
      additional_columns:
        thermal: b121
        bird_name: bird_train_glider
