# @package _global_
defaults:
  - ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
  - /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
  - _self_
experiment_name: multi_agent_policy_b072
evaluators:
  main:
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b072
          cutoff_params:
            success_altitude_m: 1177.3538
            fail_altitude_m: 485.1924
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 1084.
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: bird_train_glider
