# @package _global_
defaults:
  - ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
  - /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b010_extrapolated
  - _self_
experiment_name: multi_agent_policy_b010
evaluators:
  main:
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b010
          cutoff_params:
            success_altitude_m: 1301.3629
            fail_altitude_m: 338.703
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 928.
    observation_logger:
      additional_columns:
        thermal: b010
        bird_name: bird_train_glider
