# @package _global_
defaults:
- /env/glider/air_velocity_field@_here_: bird_easy_thermal_wind_turbulence
- _self_
random_state:
  generator_name: PCG64
  encoded_state_values: gASVLQAAAAAAAABdlChLAEsAihAXnx-IHUphCW3kQ2R2q2FSihCbBgwFRB5Yfa7iNjfGz4QEZS4=
