# @package _global_
defaults:
- /env/glider/air_velocity_field@_here_: bird_easy_thermal_wind_turbulence
- _self_
random_state:
  generator_name: PCG64
  encoded_state_values: gASVLQAAAAAAAABdlChLAEsAihDOY87LedzTwW1pFijEbp99ihAvDsw5VSiM6rRCXPPYh3BvZS4=
