defaults:
  # - /env/glider/air_velocity_filter@glider_agent_params.air_velocity_post_process.filter_kernel: exponential_kernel
  - _self_

reward_params:
  success_reward: 0.
  fail_reward: 0.
  negative_reward_enabled: true
  new_maximum_altitude_reward_enabled: true
  vertical_velocity_reward_enabled: true
cutoff_params:
  maximum_distance_from_core_m: 700.0
  success_altitude_m: 1500.0
  fail_altitude_m: 10.0
  maximum_time_without_lift_s: 600.0
  maximum_duration_s: 1800.0
time_params:
  dt_s: ???
  decision_dt_s: ???
glider_agent_params:
  roll_control_dynamics_params:
    system:
      omega_natural_frequency: 0.2
      zeta_damping_ratio: 0.5
      k_process_gain: 1.
    control:
      proportional_gain: 15.
      integral_gain: 0.66
      derivative_gain: 40.
  # air_velocity_post_process:
  #   filter_kernel:
  #     kernel_size: 10
  #     alpha: 0.25
  # air_velocity_noise:
  #   x:
  #     mean: 0.0
  #     sigma: 0.1
  #   y:
  #     mean: 0.0
  #     sigma: 0.1
  #   z:
  #     mean: 0.0
  #     sigma: 0.1
