# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: mirabell
- /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b0230_extrapolated
experiment_name: peer_informed_with_birds_b0230_mirabell
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b0230
        bird_name: Mirabell
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b0230
          cutoff_params:
            success_altitude_m: 1286.4457
            fail_altitude_m: 642.5013
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 942.5013
