# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: ronja
- /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
experiment_name: peer_informed_with_birds_b072_ronja
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: Ronja
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b072
          cutoff_params:
            success_altitude_m: 1174.0947
            fail_altitude_m: 697.6609
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 997.6609
