# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: betty
- /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b077_extrapolated
experiment_name: peer_informed_with_birds_b077_betty
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b077
        bird_name: Betty
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b077
          cutoff_params:
            success_altitude_m: 1384.3408
            fail_altitude_m: 943.8377
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 1243.8377
