# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_peer_informed_with_birds_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: ekky
- /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b121_extrapolated
experiment_name: peer_informed_with_birds_b121_ekky
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b121
        bird_name: Ekky
    env:
      env:
        params:
          inject_trajectories:
            filters:
              thermal: b121
          cutoff_params:
            success_altitude_m: 1674.746
            fail_altitude_m: 1039.6977
          agent_groups:
            student:
              initial_conditions_params:
                altitude_earth_m_mean: 1339.6977
