# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: ekky
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b010_extrapolated
experiment_name: b010_ekky
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b010
        bird_name: Ekky
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 613.3271
          cutoff_params:
            success_altitude_m: 1488.4258
            fail_altitude_m: 313.3271
