# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: peaches
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b0230_extrapolated
experiment_name: b0230_peaches
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b0230
        bird_name: Peaches
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 724.4054
          cutoff_params:
            success_altitude_m: 1481.7308
            fail_altitude_m: 424.4054
