# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: peaches
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
experiment_name: b072_peaches
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: Peaches
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 778.6158
          cutoff_params:
            success_altitude_m: 1368.2953
            fail_altitude_m: 478.61580000000004
