# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: crisps
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
experiment_name: b072_crisps
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: Crisps
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 782.6993
          cutoff_params:
            success_altitude_m: 1264.8544
            fail_altitude_m: 482.6993
