# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: balou
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
experiment_name: b072_balou
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: Balou
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 768.9641
          cutoff_params:
            success_altitude_m: 1360.0549
            fail_altitude_m: 468.96410000000003
