# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: muffine
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
experiment_name: b072_muffine
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: Muffine
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 788.039
          cutoff_params:
            success_altitude_m: 1370.7684
            fail_altitude_m: 488.039
