# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: conchito
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b072_extrapolated
experiment_name: b072_conchito
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b072
        bird_name: Conchito
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 780.9205
          cutoff_params:
            success_altitude_m: 1361.6854
            fail_altitude_m: 480.92049999999995
