# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: snowy
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b077_extrapolated
experiment_name: b077_snowy
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b077
        bird_name: Snowy
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 1039.7992
          cutoff_params:
            success_altitude_m: 1598.9964
            fail_altitude_m: 739.7991999999999
