# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: frank
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b077_extrapolated
experiment_name: b077_frank
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b077
        bird_name: Frank
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 1049.5275
          cutoff_params:
            success_altitude_m: 1738.5881
            fail_altitude_m: 749.5274999999999
