# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: cookie
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b112_extrapolated
experiment_name: b112_cookie
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b112
        bird_name: Cookie
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 1165.9651
          cutoff_params:
            success_altitude_m: 1745.8312
            fail_altitude_m: 865.9650999999999
