# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: fifi
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b112_extrapolated
experiment_name: b112_fifi
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b112
        bird_name: Fifi
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 1155.5614
          cutoff_params:
            success_altitude_m: 1762.4871
            fail_altitude_m: 855.5614
