# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: frank
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b112_extrapolated
experiment_name: b112_frank
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b112
        bird_name: Frank
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 1192.4218
          cutoff_params:
            success_altitude_m: 1752.0395
            fail_altitude_m: 892.4218000000001
