# @package _global_
defaults:
- ../initial_conditions@evaluators.main.env.env.params: realistic_single_agent_initial_conditions
- /realistic/eval/env/aerodynamics@evaluators.main.env.env.aerodynamics: balou
- override /env/glider/air_velocity_field@evaluators.main.env.env.air_velocity_field: stacked_decomposed_realistic/b121_extrapolated
experiment_name: b121_balou
evaluators:
  main:
    observation_logger:
      additional_columns:
        thermal: b121
        bird_name: Balou
    env:
      env:
        params:
          initial_conditions_params:
            altitude_earth_m_mean: 1140.9476
          cutoff_params:
            success_altitude_m: 1888.6774
            fail_altitude_m: 840.9476
